// A curated list of well-known Vancouver-area hikes — the "highest value"
// trails most people actually search for. OSM has no popularity signal, so
// this is hand-maintained. Matching is lenient (see isPopular).
export const POPULAR_HIKES: string[] = [
  // North Shore
  "Grouse Grind",
  "BCMC Trail",
  "Dog Mountain",
  "Mount Seymour",
  "First Pump Peak",
  "Mystery Lake",
  "Quarry Rock",
  "Lynn Peak",
  "Lynn Loop",
  "Norvan Falls",
  "Hanes Valley",
  "Twin Falls",
  "Rice Lake",
  "Mount Fromme",
  "Brothers Creek Trail",
  "Hollyburn Mountain",
  "Bowen Lookout",
  "Eagle Bluffs",
  "Black Mountain",
  "St. Mark's Summit",
  "Howe Sound Crest Trail",
  "Mount Strachan",
  "Cypress Falls",
  "Lighthouse Park",
  "Crown Mountain",
  "Goat Mountain",
  "Coliseum Mountain",
  "Lynn Headwaters",
  // Sea-to-Sky / Squamish
  "Stawamus Chief",
  "Sea to Summit",
  "Al's Habrich Trail",
  "Shannon Falls",
  "Slhanay",
  "Petgill Lake",
  "Brohm Lake",
  "High Falls Creek",
  "Crooked Falls",
  "Watersprite Lake",
  "Mamquam Lake",
  "Elfin Lakes",
  "Brunswick Mountain",
  "Mount Harvey",
  "The Lions",
  "Lions Binkert Trail",
  "Deeks Lake",
  "Tunnel Bluffs",
  "Garibaldi Lake",
  "Panorama Ridge",
  "Black Tusk",
  "Helm Creek",
  "Taylor Meadows",
  // Whistler / Pemberton
  "Wedgemount Lake",
  "Rainbow Lake",
  "Cheakamus Lake",
  "Brandywine Falls",
  "Brandywine Meadows",
  "Nairn Falls",
  "Train Wreck",
  "Ancient Cedars",
  "Joffre Lakes",
  "Marriott Basin",
  "Tenquille Lake",
  "Semaphore Lakes",
  "Russet Lake",
  "Blackcomb Peak",
  // Tri-Cities / Coquitlam
  "Buntzen Lake",
  "Diez Vistas",
  "Dilly-Dally Peak",
  "Eagle Mountain",
  "Sasamat Lake",
  "Lindsay Lake",
  "Dennett Lake",
  "Munro Lake",
  "Burke Mountain",
  "Widgeon Falls",
  "Jug Island",
  "Swan Falls",
  // Golden Ears / Maple Ridge
  "Golden Ears",
  "Alouette Mountain",
  "Evans Peak",
  "Lower Falls Trail",
  "Gold Creek",
  "Mike Lake",
  // Chilliwack / Fraser Valley
  "Elk Mountain",
  "Mount Thom",
  "Teapot Hill",
  "Lindeman Lake",
  "Greendrop Lake",
  "Flora Lake",
  "Mount Cheam",
  "Cheam Peak",
  "Williams Ridge",
  "Vedder Mountain",
  "Ford Mountain",
  "Sumas Mountain",
  "Chadsey Lake",
  "International Ridge",
  // North Shore — secondary
  "Baden-Powell Trail",
  "Old Buck Trail",
  "Mountain Highway",
  "Varley Trail",
  "Per Gynt Trail",
  "Three Chop Trail",
  "Mount Bishop",
  "Elsay Lake",
  "Lynn Lake",
  "Skyline Trail",
  "Whyte Lake",
  "Nelson Canyon",
  "Lawson Creek Trail",
  "Brothers Creek Fire Road",
  "Mount Seymour Main Trail",
  "Second Pump Peak",
  "Third Pump Peak",
  // Tri-Cities / Coquitlam — secondary
  "High Knoll",
  "Low Knoll",
  "Crystal Falls",
  "Sawblade Falls",
  "Coquitlam Lake View Trail",
  "Woodland Walk",
  "Minnekhada",
  "Addington Lookout",
  "Galloway Trail",
  "Quarry Rock Trail",
  // Maple Ridge / Pitt Meadows
  "Hayward Lake",
  "Rolley Lake",
  "Davis Lake",
  "Cascade Falls",
  "Kanaka Creek",
  "Cliff Falls",
  "Whonnock Lake",
  "Alouette Lake",
  "East Canyon Trail",
  "West Canyon Trail",
  "Menzies Trail",
  // Chilliwack / Fraser Valley — secondary
  "Radium Lake",
  "Mount Macfarlane",
  "Mount Rexford",
  "Slesse Memorial Trail",
  "Bear Mountain",
  "Mount McGuire",
  "Mount Laughington",
  "Pierce Lake",
  "Spoon Lake",
  "Illusion Lake",
  "Centre Creek",
  "Hope Lookout",
  "Thacker Mountain",
  // Squamish — secondary
  "Alice Lake",
  "Four Lakes Trail",
  "DeBeck's Hill",
  "Crumpit Woods",
  "Smoke Bluffs",
  "Garibaldi at Squamish",
  "Evolution Trail",
  "Jack's Trail",
  "Ray Peters Trail",
  "Wonderland Trail",
  "Mashiter Trail",
  // Whistler — secondary
  "Lost Lake",
  "Riverside Trail",
  "Valley Trail",
  "Mount Sproatt",
  "Skywalk Trail",
  "Comfortably Numb Trail",
  "Logger's Lake",
  "Crater Rim Trail",
  "Sea to Sky Trail",
  "Flank Trail",
  "Singing Pass",
  "Musical Bumps",
  // Garibaldi backcountry
  "Garibaldi Neve Traverse",
  "Sphinx Bay",
  "Burton Hut",
  // Sunshine Coast
  "Mount Daniel",
  "Pender Hill",
  "Mount Steele",
  "Tetrahedron",
  "Smuggler Cove",
  "Soames Hill",
  "Mount Elphinstone",
  "Cliff Gilker Park",
  "Skookumchuck Narrows",
  "Homesite Creek",
  "Mount Hallowell",
  // Bowen Island
  "Mount Gardner",
  "Killarney Lake",
  "Dorman Point",
  // Burnaby / Vancouver parks
  "Burnaby Mountain",
  "Burnaby Lake",
  "Deer Lake",
  "Pacific Spirit",
  "Camosun Bog",
  // Pemberton
  "Mount McLean",
  "One Mile Lake",
];

function normalize(name: string): string {
  return name
    .toLowerCase()
    .replace(/\b(trail|route|path|loop)\b/g, "")
    .replace(/[^a-z0-9 ]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

const POPULAR_NORM = POPULAR_HIKES.map(normalize);

// A trail counts as popular when its name matches a curated hike — exact, or
// one name contained in the other (with a length guard to avoid loose hits).
export function isPopular(name: string): boolean {
  const n = normalize(name);
  if (n.length < 4) return false;
  return POPULAR_NORM.some((k) => {
    if (n === k) return true;
    const shorter = Math.min(n.length, k.length);
    return shorter >= 6 && (n.includes(k) || k.includes(n));
  });
}
